Use HTTPS instead of HTTP for API calls
Using HTTP yields a 405 error. For instance, when attempting to paste a file
```
api = PastebinPython(api_dev_key=API_DEV_KEY)
api.createPasteFromFile(FILE_NAME)
```
We get the following error
```
pastebin_python.pastebin_exceptions.PastebinFileException: HTTP Error 405: Method Not Allowed
```
Using HTTPS instead fixes this.